/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cx.consumer.kafkacon.audio;
@org.apache.avro.specific.AvroGenerated
public enum Type implements org.apache.avro.generic.GenericEnumSymbol<Type> {
  REGULAR, ADVANCED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Type\",\"namespace\":\"com.cx.consumer.kafkacon.audio\",\"symbols\":[\"REGULAR\",\"ADVANCED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
